name: 'Zimperium zScan Action'
description: 'Zimperium zScan Action'
inputs:
  client_env: # REPLACE: Zimperium Environment Name
    required: true
    description: "Etc"
    #default: "$CLIENT_ENV"

  client_id: # REPLACE: Zimperium Client ID
    required: true
    description: "Etc"
    #default: "$CLIENT_ID"
  
  client_secret:
    required: true
    description: "Etc"
    #default: " ${{ secrets.ZSCAN_CLIENT_SECRET }}"

  app_file:
    required: true
    description: "Etc"
    #default: "${{ steps.apk-path.outputs.path }}"

#outputs:
#  time: # id of output
#    description: 'The time we greeted you'

runs:
  using: 'node16'
  main: 'dist/index.js'