name: "Zimperium zScan"
description: "Scan your iOS & Android mobile app binaries to identify security, privacy and compliance-related issues. Free Trial Available"
author: "Zimperium"

inputs:
  client_env: # REPLACE: Zimperium Environment Name
    required: true
    description: "Zimperium Console Client Environment Mnemonic"
    #default: "$CLIENT_ENV"
  client_id: # REPLACE: Zimperium Client ID
    required: true
    description: "zScan Console ID"
    #default: "$CLIENT_ID"
  client_secret:
    required: true
    description: "zScan API Secret"
    #default: " ${{ secrets.ZSCAN_CLIENT_SECRET }}"
  app_file:
    required: true
    description: "APK or IPA File"
    #default: "${{ steps.apk-path.outputs.path }}"

runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: alert-octagon
  color: blue
