name: 'Create PR for dist changes'
on: # manual trigger, which may create PR if any changes
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all

      - name: Create Pull Request
        # if: ${{ github.ref == 'refs/heads/main' }}
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          token: ${{ secrets.PAT_REPO_FULL }}
